### ISSUE TITLE
release package missing dependence libs 

### ISSUE THREAD

**Issue by Stvchm9703** [ajryan/RptToXml#40]
After I download the release zip v1.1.1 and run converting executable, the error has reported that it is missing assembly

 'CrystalDecisions.ReportAppServer.ClientDoc, Version=13.0.3500.0,'
 'CrystalDecisions.ReportAppServer.DataDefModel, Version=13.0.3500.0,'
'CrystalDecisions.ReportAppServer.CubeDefModel, Version=13.0.3500.0,'
'CrystalDecisions.ReportAppServer.ReportDefModel, Version=13.0.3500.0,'
'CrystalDecisions.ReportAppServer.CommLayer, Version=13.0.3500.0'

just kindly remind

**Comment by ajryan** [comment]
I haven't looked at this project in quite a while, but I believe you need to install the Crystal Reports runtime separately.

**Comment by Stvchm9703** [comment]
I solved the issue by install crystal report runtime , and thanks for your reply. ;)

**Comment by christopherpickering** [comment]
Comment for future readers -

I ran into a similar issue and after fighting for a day I gave in and read the docs on [SP28 expain. ](https://wiki.scn.sap.com/wiki/display/BOBJ/Crystal+Reports%2C+Developer+for+Visual+Studio+Downloads)

Even though Visual Studio says the ref's are valid after installing the Crystal Report Runtime you may still need to remove all the refs from the solution and re-add them.

I created a pull request to update the refs to the new version so supposedly it won't happen again on future version changes.

![image](https://user-images.githubusercontent.com/17788706/91479832-ad00ae80-e867-11ea-8ccb-aada735ed3b2.png)

**Comment by martology** [comment]
Further to the above from Christopher, anyone else coming here who is using the v1.1.1 binaries and is having errors such as `Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'CrystalDecisions.ReportAppServer.ClientDoc, Version=13.0.3500.0` be sure to download SP25 of the runtime as any higher versions will fail. This should not be an issue if you are building this yourself as this has been fixed in #41.

Here is a guide to the correct runtime versions to use:
Reference/Version=13.0.3500.0 works with Crystal runtimes 21 to 25
Reference/Version=13.0.4000.0 works with Crystal runtimes 26 and later (for now)

Any chance you could update the binary @ajryan?

**Comment by ajryan** [comment]
Thanks for the contributions all. I don't have an environment that can build this package any more! I invited @christopherpickering and @martology as contributors. Once you accept I'll set your rights so you can publish a new binary release.

Reopening until we take care of this.

**Comment by christopherpickering** [comment]
👍🏽 I'm pretty sure I have a binary around, I'll see what I can dig up.

**Comment by christopherpickering** [comment]
I built a new exe w/ SAP SP 30 on windows 10 from a fresh clone, it worked with no problems... surprise for visual studio lol. Here's a link to the release. https://github.com/ajryan/RptToXml/releases/tag/1.1.2

I'll update the readme with a message that SP 30 works.

**Comment by ajryan** [comment]
Thanks for cutting [Release 1.1.2](https://github.com/ajryan/RptToXml/releases/tag/1.1.2)!

**Comment by christopherpickering** [comment]
No problem :) This time it "just worked" lol
